### PR TITLE
Feat plugin loader

### PR DESCRIPTION
**Pull request by SuperFola**

### CODE REVIEW

**Comment by DontBelieveMe** [comment]
Hey, I've had a quick look over this and just some structural comments, but looks good :+1: - I'll detail on them tomorrow, when I've had a bit more of a think and let my brain rest :sleeping:

**Comment by apachano** [comment]
@beeperdeeper089 @DontBelieveMe Could either of you look this over and approve this? It's been sitting for a while and I bet Fola would appreciate marking it complete :)

**Comment by DontBelieveMe** [comment]
Yeah, so I'm on my phone so this isn't going to be the greatest review, but it can at least start the discussion.

One thing I was thinking was that it is cleaner to split the platform dependent code into separate files, which we can then conditionally choose to compile (or not) in CMake. This would get rid of those defines - look up the PIMPL design pattern, that's a good start. 

This is a rather big change, so discussing it on discord may be better

**Review by DontBelieveMe — APPROVED** [review]
I'm thinking that it's best to just get this merged in ASAP, and then we can talk about the finer points later.
Everything looks good from a code point of view, so as far as i'm concerned this can be merged.

**Review by vyomfadia — COMMENTED** [review]
LGTM. Like blac said, a few finer points but we should get this put in ASAP. Let's get this merged!

**Pull request merged**
